### PR TITLE
Default parsing nome

### PR DESCRIPTION
**Pull request by carla-terboven**
Resolves https://github.com/nomad-hzb/nomad-chemical-energy/issues/30

Please note that the renamed endpoints in the nomad.yaml are
"nomad_chemical_energy.schema_packages:hzb_general_process_package",
"nomad_chemical_energy.parsers:hzb_general_process_parser"

and the new nome parser is
"nomad_chemical_energy.parsers:ce_nome_general_parser",

### CODE REVIEW

**Comment by RoteKekse** [comment]
right now the mathing would only be against a sample, can you make it also such that it matches against environment ids?

**Comment by carla-terboven** [comment]
I can do that but there is no quantity to reference environments or setups in the CE_NOME_Measurement.

**Comment by carla-terboven** [comment]
So you mean I should just check for the structure without date in the parser but not use the id in any reference later?

**Comment by carla-terboven** [comment]
Please not that I had to adapt the set_sample_reference in nomad-baseclasses utilities.py to reference environment or setup ids in the sample_id field. See https://github.com/nomad-hzb/nomad-baseclasses/pull/60

**Pull request merged**
