### PR TITLE
started fixing parsing

### PR DESCRIPTION
**Pull request by RoteKekse**

### CODE REVIEW

**Comment by RoteKekse** [comment]
parsers to be checked 
- [ ] gamry parser CA, CP, LSV, LSG, CV, OCP, EIS
- [ ] dlr parser CP, CV, EIS
- [ ] NECC parser
- [ ] CENOME UVvis, XAS, TIF (no good solution here yet), massspectrometry

**Comment by carla-terboven** [comment]
Ok first a small note: I used `nomad admin uploads process <upload_id>` instead of `reprocess` but after checking with `nomad admin uploads --help` I am guessing it is correct.

**Comment by carla-terboven** [comment]
Next I wanted to compare an unpublished nomad-hzb-ce upload with the published upload in my local nomad. Here I realized that the local nomad created 56 entries but the nomad-hzb-ce nomad created 66. I am guessing this has to do with the parsers that are commented out now. But I want to be sure so I list here all entries that are in the nomad-hzb-ce and not in the local nomad.

CE-NOME_FrJo_240815_0001.0 H2O Au000001.txt
CE-NOME_FrJo_240815_0001.0 H2O Au000001.txt.archive.json
test double PTFETape 3 100724000001.txt
test double PTFETape 3 100724000001.txt.archive.json
test1234.test.txt
test1234.test.txt.archive.json
test1234.test2 (Kopie).txt
test1234.test2 (Kopie).txt.archive.json
test1234.test2.txt
test1234.test2.txt.archive.json

**Comment by carla-terboven** [comment]
Moreover I realized that some files did not get a type in the nomad-hzb-ce but they got something like "ParsedTxtFile" in the local version so maybe some additional things are fixed there?

CE-NOME_MiGo_240429_0001.SA_5_MM.csv
P-O2D109.pump.csv
calib_30min_0.1ppm.ABS
testO2.oxy.xlsx

**Comment by RoteKekse** [comment]
> Moreover I realized that some files did not get a type in the nomad-hzb-ce but they got something like "ParsedTxtFile" in the local version so maybe some additional things are fixed there?
> 
> CE-NOME_MiGo_240429_0001.SA_5_MM.csv P-O2D109.pump.csv calib_30min_0.1ppm.ABS testO2.oxy.xlsx

yes i added a default type to all files

**Comment by RoteKekse** [comment]
> Next I wanted to compare an unpublished nomad-hzb-ce upload with the published upload in my local nomad. Here I realized that the local nomad created 56 entries but the nomad-hzb-ce nomad created 66. I am guessing this has to do with the parsers that are commented out now. But I want to be sure so I list here all entries that are in the nomad-hzb-ce and not in the local nomad.
> 
> CE-NOME_FrJo_240815_0001.0 H2O Au000001.txt CE-NOME_FrJo_240815_0001.0 H2O Au000001.txt.archive.json test double PTFETape 3 100724000001.txt test double PTFETape 3 100724000001.txt.archive.json test1234.test.txt test1234.test.txt.archive.json test1234.test2 (Kopie).txt test1234.test2 (Kopie).txt.archive.json test1234.test2.txt test1234.test2.txt.archive.json

oh interessting what kind of files are they?

**Comment by carla-terboven** [comment]
> Next I wanted to compare an unpublished nomad-hzb-ce upload with the published upload in my local nomad. Here I realized that the local nomad created 56 entries but the nomad-hzb-ce nomad created 66. I am guessing this has to do with the parsers that are commented out now. But I want to be sure so I list here all entries that are in the nomad-hzb-ce and not in the local nomad.
> 
> CE-NOME_FrJo_240815_0001.0 H2O Au000001.txt CE-NOME_FrJo_240815_0001.0 H2O Au000001.txt.archive.json test double PTFETape 3 100724000001.txt test double PTFETape 3 100724000001.txt.archive.json test1234.test.txt test1234.test.txt.archive.json test1234.test2 (Kopie).txt test1234.test2 (Kopie).txt.archive.json test1234.test2.txt test1234.test2.txt.archive.json

Ok my fault. This worked when I added the massspectrometry_parser.

**Comment by carla-terboven** [comment]
I added tempfile to parse TIF images. Not sure if it is the most straight forward way to do it. 
Please check https://github.com/nomad-hzb/nomad-chemical-energy/pull/29/commits/fb05e46530be4e2113fbeb9413d82f27eb06f1d4

**Comment by RoteKekse** [comment]
that now all looks good from my side, is there sth left to test?

**Comment by carla-terboven** [comment]
Looks good for me too :crossed_fingers:

**Pull request merged**
